// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exceptionframe.piqi.proto

#ifndef PROTOBUF_exceptionframe_2epiqi_2eproto__INCLUDED
#define PROTOBUF_exceptionframe_2epiqi_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_exceptionframe_2epiqi_2eproto();
void protobuf_AssignDesc_exceptionframe_2epiqi_2eproto();
void protobuf_ShutdownFile_exceptionframe_2epiqi_2eproto();

class exception_frame;

// ===================================================================

class exception_frame : public ::google::protobuf::Message {
 public:
  exception_frame();
  virtual ~exception_frame();
  
  exception_frame(const exception_frame& from);
  
  inline exception_frame& operator=(const exception_frame& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const exception_frame& default_instance();
  
  void Swap(exception_frame* other);
  
  // implements Message ----------------------------------------------
  
  exception_frame* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const exception_frame& from);
  void MergeFrom(const exception_frame& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint64 exception_number = 1;
  inline bool has_exception_number() const;
  inline void clear_exception_number();
  static const int kExceptionNumberFieldNumber = 1;
  inline ::google::protobuf::uint64 exception_number() const;
  inline void set_exception_number(::google::protobuf::uint64 value);
  
  // optional uint64 thread_id = 2;
  inline bool has_thread_id() const;
  inline void clear_thread_id();
  static const int kThreadIdFieldNumber = 2;
  inline ::google::protobuf::uint64 thread_id() const;
  inline void set_thread_id(::google::protobuf::uint64 value);
  
  // required uint64 from_addr = 3;
  inline bool has_from_addr() const;
  inline void clear_from_addr();
  static const int kFromAddrFieldNumber = 3;
  inline ::google::protobuf::uint64 from_addr() const;
  inline void set_from_addr(::google::protobuf::uint64 value);
  
  // required uint64 to_addr = 4;
  inline bool has_to_addr() const;
  inline void clear_to_addr();
  static const int kToAddrFieldNumber = 4;
  inline ::google::protobuf::uint64 to_addr() const;
  inline void set_to_addr(::google::protobuf::uint64 value);
  
  // @@protoc_insertion_point(class_scope:exception_frame)
 private:
  inline void set_has_exception_number();
  inline void clear_has_exception_number();
  inline void set_has_thread_id();
  inline void clear_has_thread_id();
  inline void set_has_from_addr();
  inline void clear_has_from_addr();
  inline void set_has_to_addr();
  inline void clear_has_to_addr();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 exception_number_;
  ::google::protobuf::uint64 thread_id_;
  ::google::protobuf::uint64 from_addr_;
  ::google::protobuf::uint64 to_addr_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_exceptionframe_2epiqi_2eproto();
  friend void protobuf_AssignDesc_exceptionframe_2epiqi_2eproto();
  friend void protobuf_ShutdownFile_exceptionframe_2epiqi_2eproto();
  
  void InitAsDefaultInstance();
  static exception_frame* default_instance_;
};
// ===================================================================


// ===================================================================

// exception_frame

// required uint64 exception_number = 1;
inline bool exception_frame::has_exception_number() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void exception_frame::set_has_exception_number() {
  _has_bits_[0] |= 0x00000001u;
}
inline void exception_frame::clear_has_exception_number() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void exception_frame::clear_exception_number() {
  exception_number_ = GOOGLE_ULONGLONG(0);
  clear_has_exception_number();
}
inline ::google::protobuf::uint64 exception_frame::exception_number() const {
  return exception_number_;
}
inline void exception_frame::set_exception_number(::google::protobuf::uint64 value) {
  set_has_exception_number();
  exception_number_ = value;
}

// optional uint64 thread_id = 2;
inline bool exception_frame::has_thread_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void exception_frame::set_has_thread_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void exception_frame::clear_has_thread_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void exception_frame::clear_thread_id() {
  thread_id_ = GOOGLE_ULONGLONG(0);
  clear_has_thread_id();
}
inline ::google::protobuf::uint64 exception_frame::thread_id() const {
  return thread_id_;
}
inline void exception_frame::set_thread_id(::google::protobuf::uint64 value) {
  set_has_thread_id();
  thread_id_ = value;
}

// required uint64 from_addr = 3;
inline bool exception_frame::has_from_addr() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void exception_frame::set_has_from_addr() {
  _has_bits_[0] |= 0x00000004u;
}
inline void exception_frame::clear_has_from_addr() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void exception_frame::clear_from_addr() {
  from_addr_ = GOOGLE_ULONGLONG(0);
  clear_has_from_addr();
}
inline ::google::protobuf::uint64 exception_frame::from_addr() const {
  return from_addr_;
}
inline void exception_frame::set_from_addr(::google::protobuf::uint64 value) {
  set_has_from_addr();
  from_addr_ = value;
}

// required uint64 to_addr = 4;
inline bool exception_frame::has_to_addr() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void exception_frame::set_has_to_addr() {
  _has_bits_[0] |= 0x00000008u;
}
inline void exception_frame::clear_has_to_addr() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void exception_frame::clear_to_addr() {
  to_addr_ = GOOGLE_ULONGLONG(0);
  clear_has_to_addr();
}
inline ::google::protobuf::uint64 exception_frame::to_addr() const {
  return to_addr_;
}
inline void exception_frame::set_to_addr(::google::protobuf::uint64 value) {
  set_has_to_addr();
  to_addr_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_exceptionframe_2epiqi_2eproto__INCLUDED
