// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: taintintroframe.piqi.proto

#ifndef PROTOBUF_taintintroframe_2epiqi_2eproto__INCLUDED
#define PROTOBUF_taintintroframe_2epiqi_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_taintintroframe_2epiqi_2eproto();
void protobuf_AssignDesc_taintintroframe_2epiqi_2eproto();
void protobuf_ShutdownFile_taintintroframe_2epiqi_2eproto();

class taint_intro_frame;
class taint_intro_list;
class taint_intro;

// ===================================================================

class taint_intro_frame : public ::google::protobuf::Message {
 public:
  taint_intro_frame();
  virtual ~taint_intro_frame();
  
  taint_intro_frame(const taint_intro_frame& from);
  
  inline taint_intro_frame& operator=(const taint_intro_frame& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const taint_intro_frame& default_instance();
  
  void Swap(taint_intro_frame* other);
  
  // implements Message ----------------------------------------------
  
  taint_intro_frame* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const taint_intro_frame& from);
  void MergeFrom(const taint_intro_frame& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required .taint_intro_list taint_intro_list = 1;
  inline bool has_taint_intro_list() const;
  inline void clear_taint_intro_list();
  static const int kTaintIntroListFieldNumber = 1;
  inline const ::taint_intro_list& taint_intro_list() const;
  inline ::taint_intro_list* mutable_taint_intro_list();
  inline ::taint_intro_list* release_taint_intro_list();
  
  // @@protoc_insertion_point(class_scope:taint_intro_frame)
 private:
  inline void set_has_taint_intro_list();
  inline void clear_has_taint_intro_list();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::taint_intro_list* taint_intro_list_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_taintintroframe_2epiqi_2eproto();
  friend void protobuf_AssignDesc_taintintroframe_2epiqi_2eproto();
  friend void protobuf_ShutdownFile_taintintroframe_2epiqi_2eproto();
  
  void InitAsDefaultInstance();
  static taint_intro_frame* default_instance_;
};
// -------------------------------------------------------------------

class taint_intro_list : public ::google::protobuf::Message {
 public:
  taint_intro_list();
  virtual ~taint_intro_list();
  
  taint_intro_list(const taint_intro_list& from);
  
  inline taint_intro_list& operator=(const taint_intro_list& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const taint_intro_list& default_instance();
  
  void Swap(taint_intro_list* other);
  
  // implements Message ----------------------------------------------
  
  taint_intro_list* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const taint_intro_list& from);
  void MergeFrom(const taint_intro_list& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .taint_intro elem = 1;
  inline int elem_size() const;
  inline void clear_elem();
  static const int kElemFieldNumber = 1;
  inline const ::taint_intro& elem(int index) const;
  inline ::taint_intro* mutable_elem(int index);
  inline ::taint_intro* add_elem();
  inline const ::google::protobuf::RepeatedPtrField< ::taint_intro >&
      elem() const;
  inline ::google::protobuf::RepeatedPtrField< ::taint_intro >*
      mutable_elem();
  
  // @@protoc_insertion_point(class_scope:taint_intro_list)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::taint_intro > elem_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_taintintroframe_2epiqi_2eproto();
  friend void protobuf_AssignDesc_taintintroframe_2epiqi_2eproto();
  friend void protobuf_ShutdownFile_taintintroframe_2epiqi_2eproto();
  
  void InitAsDefaultInstance();
  static taint_intro_list* default_instance_;
};
// -------------------------------------------------------------------

class taint_intro : public ::google::protobuf::Message {
 public:
  taint_intro();
  virtual ~taint_intro();
  
  taint_intro(const taint_intro& from);
  
  inline taint_intro& operator=(const taint_intro& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const taint_intro& default_instance();
  
  void Swap(taint_intro* other);
  
  // implements Message ----------------------------------------------
  
  taint_intro* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const taint_intro& from);
  void MergeFrom(const taint_intro& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint64 addr = 1;
  inline bool has_addr() const;
  inline void clear_addr();
  static const int kAddrFieldNumber = 1;
  inline ::google::protobuf::uint64 addr() const;
  inline void set_addr(::google::protobuf::uint64 value);
  
  // required uint64 taint_id = 2;
  inline bool has_taint_id() const;
  inline void clear_taint_id();
  static const int kTaintIdFieldNumber = 2;
  inline ::google::protobuf::uint64 taint_id() const;
  inline void set_taint_id(::google::protobuf::uint64 value);
  
  // @@protoc_insertion_point(class_scope:taint_intro)
 private:
  inline void set_has_addr();
  inline void clear_has_addr();
  inline void set_has_taint_id();
  inline void clear_has_taint_id();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 addr_;
  ::google::protobuf::uint64 taint_id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_taintintroframe_2epiqi_2eproto();
  friend void protobuf_AssignDesc_taintintroframe_2epiqi_2eproto();
  friend void protobuf_ShutdownFile_taintintroframe_2epiqi_2eproto();
  
  void InitAsDefaultInstance();
  static taint_intro* default_instance_;
};
// ===================================================================


// ===================================================================

// taint_intro_frame

// required .taint_intro_list taint_intro_list = 1;
inline bool taint_intro_frame::has_taint_intro_list() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void taint_intro_frame::set_has_taint_intro_list() {
  _has_bits_[0] |= 0x00000001u;
}
inline void taint_intro_frame::clear_has_taint_intro_list() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void taint_intro_frame::clear_taint_intro_list() {
  if (taint_intro_list_ != NULL) taint_intro_list_->::taint_intro_list::Clear();
  clear_has_taint_intro_list();
}
inline const ::taint_intro_list& taint_intro_frame::taint_intro_list() const {
  return taint_intro_list_ != NULL ? *taint_intro_list_ : *default_instance_->taint_intro_list_;
}
inline ::taint_intro_list* taint_intro_frame::mutable_taint_intro_list() {
  set_has_taint_intro_list();
  if (taint_intro_list_ == NULL) taint_intro_list_ = new ::taint_intro_list;
  return taint_intro_list_;
}
inline ::taint_intro_list* taint_intro_frame::release_taint_intro_list() {
  clear_has_taint_intro_list();
  ::taint_intro_list* temp = taint_intro_list_;
  taint_intro_list_ = NULL;
  return temp;
}

// -------------------------------------------------------------------

// taint_intro_list

// repeated .taint_intro elem = 1;
inline int taint_intro_list::elem_size() const {
  return elem_.size();
}
inline void taint_intro_list::clear_elem() {
  elem_.Clear();
}
inline const ::taint_intro& taint_intro_list::elem(int index) const {
  return elem_.Get(index);
}
inline ::taint_intro* taint_intro_list::mutable_elem(int index) {
  return elem_.Mutable(index);
}
inline ::taint_intro* taint_intro_list::add_elem() {
  return elem_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::taint_intro >&
taint_intro_list::elem() const {
  return elem_;
}
inline ::google::protobuf::RepeatedPtrField< ::taint_intro >*
taint_intro_list::mutable_elem() {
  return &elem_;
}

// -------------------------------------------------------------------

// taint_intro

// required uint64 addr = 1;
inline bool taint_intro::has_addr() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void taint_intro::set_has_addr() {
  _has_bits_[0] |= 0x00000001u;
}
inline void taint_intro::clear_has_addr() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void taint_intro::clear_addr() {
  addr_ = GOOGLE_ULONGLONG(0);
  clear_has_addr();
}
inline ::google::protobuf::uint64 taint_intro::addr() const {
  return addr_;
}
inline void taint_intro::set_addr(::google::protobuf::uint64 value) {
  set_has_addr();
  addr_ = value;
}

// required uint64 taint_id = 2;
inline bool taint_intro::has_taint_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void taint_intro::set_has_taint_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void taint_intro::clear_has_taint_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void taint_intro::clear_taint_id() {
  taint_id_ = GOOGLE_ULONGLONG(0);
  clear_has_taint_id();
}
inline ::google::protobuf::uint64 taint_intro::taint_id() const {
  return taint_id_;
}
inline void taint_intro::set_taint_id(::google::protobuf::uint64 value) {
  set_has_taint_id();
  taint_id_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_taintintroframe_2epiqi_2eproto__INCLUDED
