// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: syscallframe.piqi.proto

#ifndef PROTOBUF_syscallframe_2epiqi_2eproto__INCLUDED
#define PROTOBUF_syscallframe_2epiqi_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_syscallframe_2epiqi_2eproto();
void protobuf_AssignDesc_syscallframe_2epiqi_2eproto();
void protobuf_ShutdownFile_syscallframe_2epiqi_2eproto();

class syscall_frame;
class argument_list;

// ===================================================================

class syscall_frame : public ::google::protobuf::Message {
 public:
  syscall_frame();
  virtual ~syscall_frame();
  
  syscall_frame(const syscall_frame& from);
  
  inline syscall_frame& operator=(const syscall_frame& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const syscall_frame& default_instance();
  
  void Swap(syscall_frame* other);
  
  // implements Message ----------------------------------------------
  
  syscall_frame* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const syscall_frame& from);
  void MergeFrom(const syscall_frame& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint64 address = 1;
  inline bool has_address() const;
  inline void clear_address();
  static const int kAddressFieldNumber = 1;
  inline ::google::protobuf::uint64 address() const;
  inline void set_address(::google::protobuf::uint64 value);
  
  // required uint64 thread_id = 2;
  inline bool has_thread_id() const;
  inline void clear_thread_id();
  static const int kThreadIdFieldNumber = 2;
  inline ::google::protobuf::uint64 thread_id() const;
  inline void set_thread_id(::google::protobuf::uint64 value);
  
  // required uint64 number = 3;
  inline bool has_number() const;
  inline void clear_number();
  static const int kNumberFieldNumber = 3;
  inline ::google::protobuf::uint64 number() const;
  inline void set_number(::google::protobuf::uint64 value);
  
  // required .argument_list argument_list = 4;
  inline bool has_argument_list() const;
  inline void clear_argument_list();
  static const int kArgumentListFieldNumber = 4;
  inline const ::argument_list& argument_list() const;
  inline ::argument_list* mutable_argument_list();
  inline ::argument_list* release_argument_list();
  
  // @@protoc_insertion_point(class_scope:syscall_frame)
 private:
  inline void set_has_address();
  inline void clear_has_address();
  inline void set_has_thread_id();
  inline void clear_has_thread_id();
  inline void set_has_number();
  inline void clear_has_number();
  inline void set_has_argument_list();
  inline void clear_has_argument_list();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint64 address_;
  ::google::protobuf::uint64 thread_id_;
  ::google::protobuf::uint64 number_;
  ::argument_list* argument_list_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_syscallframe_2epiqi_2eproto();
  friend void protobuf_AssignDesc_syscallframe_2epiqi_2eproto();
  friend void protobuf_ShutdownFile_syscallframe_2epiqi_2eproto();
  
  void InitAsDefaultInstance();
  static syscall_frame* default_instance_;
};
// -------------------------------------------------------------------

class argument_list : public ::google::protobuf::Message {
 public:
  argument_list();
  virtual ~argument_list();
  
  argument_list(const argument_list& from);
  
  inline argument_list& operator=(const argument_list& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const argument_list& default_instance();
  
  void Swap(argument_list* other);
  
  // implements Message ----------------------------------------------
  
  argument_list* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const argument_list& from);
  void MergeFrom(const argument_list& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated sint64 elem = 1;
  inline int elem_size() const;
  inline void clear_elem();
  static const int kElemFieldNumber = 1;
  inline ::google::protobuf::int64 elem(int index) const;
  inline void set_elem(int index, ::google::protobuf::int64 value);
  inline void add_elem(::google::protobuf::int64 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      elem() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_elem();
  
  // @@protoc_insertion_point(class_scope:argument_list)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > elem_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_syscallframe_2epiqi_2eproto();
  friend void protobuf_AssignDesc_syscallframe_2epiqi_2eproto();
  friend void protobuf_ShutdownFile_syscallframe_2epiqi_2eproto();
  
  void InitAsDefaultInstance();
  static argument_list* default_instance_;
};
// ===================================================================


// ===================================================================

// syscall_frame

// required uint64 address = 1;
inline bool syscall_frame::has_address() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void syscall_frame::set_has_address() {
  _has_bits_[0] |= 0x00000001u;
}
inline void syscall_frame::clear_has_address() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void syscall_frame::clear_address() {
  address_ = GOOGLE_ULONGLONG(0);
  clear_has_address();
}
inline ::google::protobuf::uint64 syscall_frame::address() const {
  return address_;
}
inline void syscall_frame::set_address(::google::protobuf::uint64 value) {
  set_has_address();
  address_ = value;
}

// required uint64 thread_id = 2;
inline bool syscall_frame::has_thread_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void syscall_frame::set_has_thread_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void syscall_frame::clear_has_thread_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void syscall_frame::clear_thread_id() {
  thread_id_ = GOOGLE_ULONGLONG(0);
  clear_has_thread_id();
}
inline ::google::protobuf::uint64 syscall_frame::thread_id() const {
  return thread_id_;
}
inline void syscall_frame::set_thread_id(::google::protobuf::uint64 value) {
  set_has_thread_id();
  thread_id_ = value;
}

// required uint64 number = 3;
inline bool syscall_frame::has_number() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void syscall_frame::set_has_number() {
  _has_bits_[0] |= 0x00000004u;
}
inline void syscall_frame::clear_has_number() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void syscall_frame::clear_number() {
  number_ = GOOGLE_ULONGLONG(0);
  clear_has_number();
}
inline ::google::protobuf::uint64 syscall_frame::number() const {
  return number_;
}
inline void syscall_frame::set_number(::google::protobuf::uint64 value) {
  set_has_number();
  number_ = value;
}

// required .argument_list argument_list = 4;
inline bool syscall_frame::has_argument_list() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void syscall_frame::set_has_argument_list() {
  _has_bits_[0] |= 0x00000008u;
}
inline void syscall_frame::clear_has_argument_list() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void syscall_frame::clear_argument_list() {
  if (argument_list_ != NULL) argument_list_->::argument_list::Clear();
  clear_has_argument_list();
}
inline const ::argument_list& syscall_frame::argument_list() const {
  return argument_list_ != NULL ? *argument_list_ : *default_instance_->argument_list_;
}
inline ::argument_list* syscall_frame::mutable_argument_list() {
  set_has_argument_list();
  if (argument_list_ == NULL) argument_list_ = new ::argument_list;
  return argument_list_;
}
inline ::argument_list* syscall_frame::release_argument_list() {
  clear_has_argument_list();
  ::argument_list* temp = argument_list_;
  argument_list_ = NULL;
  return temp;
}

// -------------------------------------------------------------------

// argument_list

// repeated sint64 elem = 1;
inline int argument_list::elem_size() const {
  return elem_.size();
}
inline void argument_list::clear_elem() {
  elem_.Clear();
}
inline ::google::protobuf::int64 argument_list::elem(int index) const {
  return elem_.Get(index);
}
inline void argument_list::set_elem(int index, ::google::protobuf::int64 value) {
  elem_.Set(index, value);
}
inline void argument_list::add_elem(::google::protobuf::int64 value) {
  elem_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
argument_list::elem() const {
  return elem_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
argument_list::mutable_elem() {
  return &elem_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_syscallframe_2epiqi_2eproto__INCLUDED
